# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e384a94e4f294123c2a90cdd1d48b912"
name = "discount-store-app"
handle = "discount-store-app"
application_url = "https://emerald-excluded-senior-ind.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-6a2d63c8.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://emerald-excluded-senior-ind.trycloudflare.com/auth/callback",
  "https://emerald-excluded-senior-ind.trycloudflare.com/auth/shopify/callback",
  "https://emerald-excluded-senior-ind.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
